import {
  Product,
  BulkPool,
  CreditProfile,
  Order,
  LogisticsRoute,
  DeliveryRequest,
  Collateral,
  BNPLApplication,
  PlatformMetrics,
  AppUser,
} from "../types";

export const defaultUser: AppUser = {
  id: "user_1",
  name: "Chidi Okonkwo",
  role: "buyer",
  businessName: "Chidi's Retail Mart",
};

export const allUsers: AppUser[] = [
  defaultUser,
  {
    id: "user_2",
    name: "Adebayo Ogunlesi",
    role: "producer",
    businessName: "Aba Leather Works Ltd",
  },
  {
    id: "user_3",
    name: "Aisha Mohammed",
    role: "lender",
    businessName: "Cooperative Finance Trust",
  },
  {
    id: "user_4",
    name: "Emeka Nwosu",
    role: "buyer",
    businessName: "Emeka's Wholesale Goods",
  },
  {
    id: "user_5",
    name: "Funke Adeyemi",
    role: "producer",
    businessName: "Ibadan Agro Processors",
  },
];

export const products: Product[] = [
  {
    id: "prod_1",
    title: "Premium Aba Leather Soles",
    category: "Footwear & Leather",
    location: "Aba - Enyimba Industrial Layout",
    region: "Aba",
    producerName: "Aba Leather Works Ltd",
    producerId: "user_2",
    totalCapacity: 50000,
    idleCapacityPct: 35,
    pricePerUnit: 850,
    moq: 500,
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&q=80",
    verified: true,
    description:
      "High-quality finished leather soles made from locally sourced cowhide. Durable, flexible, and export-grade quality used by shoemakers across West Africa.",
    unit: "pairs",
    tierPricing: [
      { minQty: 500, maxQty: 999, pricePerUnit: 850 },
      { minQty: 1000, maxQty: 4999, pricePerUnit: 780 },
      { minQty: 5000, maxQty: null, pricePerUnit: 720 },
    ],
    createdAt: "2024-10-15",
  },
  {
    id: "prod_2",
    title: "Organic Cotton Bales (Kano Spun)",
    category: "Textiles & Apparel",
    location: "Kano - Sharada Industrial Zone",
    region: "Kano",
    producerName: "Kano Textile Mills",
    producerId: "user_2",
    totalCapacity: 120000,
    idleCapacityPct: 42,
    pricePerUnit: 3200,
    moq: 100,
    image: "https://images.unsplash.com/photo-1583842742206-0dd1c29c9b5e?w=400&q=80",
    verified: true,
    description:
      "Premium-grade organic cotton bales, ginned and spun in Kano. Perfect for textile manufacturers producing high-end apparel and home furnishings.",
    unit: "kg",
    tierPricing: [
      { minQty: 100, maxQty: 499, pricePerUnit: 3200 },
      { minQty: 500, maxQty: 1999, pricePerUnit: 2950 },
      { minQty: 2000, maxQty: null, pricePerUnit: 2700 },
    ],
    createdAt: "2024-09-20",
  },
  {
    id: "prod_3",
    title: "Ibadan Premium Cassava Flour (Elubo)",
    category: "Agro-Processing",
    location: "Ibadan - Oyo State",
    region: "Ibadan",
    producerName: "Ibadan Agro Processors",
    producerId: "user_5",
    totalCapacity: 80000,
    idleCapacityPct: 28,
    pricePerUnit: 450,
    moq: 200,
    image: "https://images.unsplash.com/photo-1601814933822-3bd0dd8c6a4e?w=400&q=80",
    verified: true,
    description:
      "High-grade cassava flour (Elubo) processed in Ibadan. Ideal for industrial baking, confectionery, and traditional food manufacturing. Premium quality, machine-processed.",
    unit: "kg",
    tierPricing: [
      { minQty: 200, maxQty: 999, pricePerUnit: 450 },
      { minQty: 1000, maxQty: 4999, pricePerUnit: 400 },
      { minQty: 5000, maxQty: null, pricePerUnit: 360 },
    ],
    createdAt: "2024-11-01",
  },
  {
    id: "prod_4",
    title: "Corrugated Packaging Boxes (Ikeja)",
    category: "Plastics & Packaging",
    location: "Lagos - Ikeja Industrial Area",
    region: "Lagos",
    producerName: "Lagos Packaging Solutions",
    producerId: "user_5",
    totalCapacity: 200000,
    idleCapacityPct: 22,
    pricePerUnit: 180,
    moq: 1000,
    image: "https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=400&q=80",
    verified: true,
    description:
      "Heavy-duty corrugated cardboard boxes manufactured in Ikeja. Available in standard and custom sizes. Suitable for export packaging, FMCG and industrial goods.",
    unit: "pieces",
    tierPricing: [
      { minQty: 1000, maxQty: 4999, pricePerUnit: 180 },
      { minQty: 5000, maxQty: 19999, pricePerUnit: 155 },
      { minQty: 20000, maxQty: null, pricePerUnit: 130 },
    ],
    createdAt: "2024-10-05",
  },
  {
    id: "prod_5",
    title: "Recycled HDPE Granules",
    category: "Plastics & Packaging",
    location: "Onitsha - Anambra State",
    region: "Onitsha",
    producerName: "Onitsha Plastic Recycling Co",
    producerId: "user_2",
    totalCapacity: 60000,
    idleCapacityPct: 45,
    pricePerUnit: 520,
    moq: 500,
    image: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=400&q=80",
    verified: false,
    description:
      "Washed and processed recycled HDPE granules suitable for blow molding and injection molding applications. Cost-effective alternative to virgin plastic.",
    unit: "kg",
    tierPricing: [
      { minQty: 500, maxQty: 1999, pricePerUnit: 520 },
      { minQty: 2000, maxQty: null, pricePerUnit: 480 },
    ],
    createdAt: "2024-11-10",
  },
  {
    id: "prod_6",
    title: "Nnewi Fabricated Machine Parts",
    category: "Light Machinery",
    location: "Nnewi - Anambra State",
    region: "Nnewi",
    producerName: "Nnewi Engineering Works",
    producerId: "user_2",
    totalCapacity: 15000,
    idleCapacityPct: 55,
    pricePerUnit: 15000,
    moq: 10,
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=400&q=80",
    verified: true,
    description:
      "Custom-fabricated industrial machine components and spare parts. Made-to-order with precision engineering. Serves the manufacturing and agro-processing sectors.",
    unit: "pieces",
    tierPricing: [
      { minQty: 10, maxQty: 49, pricePerUnit: 15000 },
      { minQty: 50, maxQty: null, pricePerUnit: 13500 },
    ],
    createdAt: "2024-08-15",
  },
  {
    id: "prod_7",
    title: "Aba Handcrafted Leather Belts (Wholesale)",
    category: "Footwear & Leather",
    location: "Aba - Enyimba Industrial Layout",
    region: "Aba",
    producerName: "Aba Leather Works Ltd",
    producerId: "user_2",
    totalCapacity: 30000,
    idleCapacityPct: 30,
    pricePerUnit: 1200,
    moq: 200,
    image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=400&q=80",
    verified: true,
    description:
      "Genuine leather belts handcrafted by Aba artisans. Durable full-grain leather with brass buckles. Available in black, brown, and tan. Export quality.",
    unit: "pieces",
    tierPricing: [
      { minQty: 200, maxQty: 999, pricePerUnit: 1200 },
      { minQty: 1000, maxQty: null, pricePerUnit: 1050 },
    ],
    createdAt: "2024-10-01",
  },
  {
    id: "prod_8",
    title: "Kano Organic Shea Butter (Refined)",
    category: "Chemical Raw Materials",
    location: "Kano - Sharada Industrial Zone",
    region: "Kano",
    producerName: "Kano Textile Mills",
    producerId: "user_2",
    totalCapacity: 40000,
    idleCapacityPct: 38,
    pricePerUnit: 2800,
    moq: 50,
    image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=400&q=80",
    verified: true,
    description:
      "Refined organic shea butter from Kano. Suitable for cosmetic manufacturing, soap production, and food-grade applications. Certified organic, chemical-free processing.",
    unit: "kg",
    tierPricing: [
      { minQty: 50, maxQty: 199, pricePerUnit: 2800 },
      { minQty: 200, maxQty: 999, pricePerUnit: 2500 },
      { minQty: 1000, maxQty: null, pricePerUnit: 2200 },
    ],
    createdAt: "2024-09-10",
  },
  {
    id: "prod_9",
    title: "Lagos Industrial Packaging Film",
    category: "Plastics & Packaging",
    location: "Lagos - Ikeja Industrial Area",
    region: "Lagos",
    producerName: "Lagos Packaging Solutions",
    producerId: "user_5",
    totalCapacity: 100000,
    idleCapacityPct: 18,
    pricePerUnit: 950,
    moq: 100,
    image: "https://images.unsplash.com/photo-1604079628040-94301bb21b91?w=400&q=80",
    verified: true,
    description:
      "High-strength industrial stretch film and shrink wrap. Used for pallet wrapping, goods protection, and export packaging. UV-stabilized options available.",
    unit: "kg",
    tierPricing: [
      { minQty: 100, maxQty: 499, pricePerUnit: 950 },
      { minQty: 500, maxQty: null, pricePerUnit: 850 },
    ],
    createdAt: "2024-11-05",
  },
  {
    id: "prod_10",
    title: "Ibadan Soybean Cake (Animal Feed)",
    category: "Agro-Processing",
    location: "Ibadan - Oyo State",
    region: "Ibadan",
    producerName: "Ibadan Agro Processors",
    producerId: "user_5",
    totalCapacity: 90000,
    idleCapacityPct: 25,
    pricePerUnit: 380,
    moq: 500,
    image: "https://images.unsplash.com/photo-1598532163257-ae3c6b2524b6?w=400&q=80",
    verified: true,
    description:
      "High-protein soybean cake for animal feed manufacturing. Processed using modern solvent extraction. 48% protein content minimum. Consistent quality batch to batch.",
    unit: "kg",
    tierPricing: [
      { minQty: 500, maxQty: 1999, pricePerUnit: 380 },
      { minQty: 2000, maxQty: 9999, pricePerUnit: 340 },
      { minQty: 10000, maxQty: null, pricePerUnit: 300 },
    ],
    createdAt: "2024-10-20",
  },
];

export const bulkPools: BulkPool[] = [
  {
    id: "pool_1",
    title: "Kano Organic Cotton Bales Bulk Buy",
    category: "Textiles & Apparel",
    targetQuantity: 5000,
    currentQuantity: 3450,
    unitDiscountPrice: 2700,
    originalPrice: 3200,
    deadline: "2025-03-15",
    participantsCount: 12,
    unit: "kg",
    description:
      "Aggregating demand for Kano organic cotton to unlock the 2000kg+ tier price. Current participants include 5 garment manufacturers and 7 textile traders.",
    participants: [
      { id: "p1", name: "Lagos Garment Factory", quantity: 800, joinedAt: "2025-01-10" },
      { id: "p2", name: "Abuja Textiles Ltd", quantity: 500, joinedAt: "2025-01-12" },
      { id: "p3", name: "Port Harcourt Fabrics", quantity: 350, joinedAt: "2025-01-15" },
      { id: "p4", name: "Ibadan Apparel Makers", quantity: 600, joinedAt: "2025-01-18" },
      { id: "p5", name: "Kano Dyeing Cooperative", quantity: 400, joinedAt: "2025-01-20" },
      { id: "p6", name: "Onitsha Textile Market", quantity: 800, joinedAt: "2025-01-22" },
    ],
  },
  {
    id: "pool_2",
    title: "Ibadan Cassava Flour Cooperative Run",
    category: "Agro-Processing",
    targetQuantity: 10000,
    currentQuantity: 7200,
    unitDiscountPrice: 360,
    originalPrice: 450,
    deadline: "2025-03-01",
    participantsCount: 24,
    unit: "kg",
    description:
      "Bulk purchase of premium cassava flour for bakery and confectionery businesses. The 5000kg+ tier price unlocks 20% savings for all participants.",
    participants: [
      { id: "p7", name: "Lagos Bakery Chain", quantity: 2000, joinedAt: "2025-01-05" },
      { id: "p8", name: "Ibadan Confectionery", quantity: 1000, joinedAt: "2025-01-08" },
      { id: "p9", name: "Abuja Food Processors", quantity: 1500, joinedAt: "2025-01-11" },
    ],
  },
  {
    id: "pool_3",
    title: "Aba Leather Bulk Procurement",
    category: "Footwear & Leather",
    targetQuantity: 10000,
    currentQuantity: 4800,
    unitDiscountPrice: 720,
    originalPrice: 850,
    deadline: "2025-04-01",
    participantsCount: 8,
    unit: "pairs",
    description:
      "Group purchase of premium Aba leather soles. Target is the 5000+ pairs tier. Open to footwear manufacturers, shoe retailers, and exporters.",
    participants: [
      { id: "p10", name: "ShoeMart Nigeria", quantity: 1500, joinedAt: "2025-01-15" },
      { id: "p11", name: "Abuja Footwear Ltd", quantity: 1000, joinedAt: "2025-01-18" },
    ],
  },
  {
    id: "pool_4",
    title: "Lagos Packaging Materials Consortium",
    category: "Plastics & Packaging",
    targetQuantity: 50000,
    currentQuantity: 28500,
    unitDiscountPrice: 130,
    originalPrice: 180,
    deadline: "2025-03-20",
    participantsCount: 15,
    unit: "pieces",
    description:
      "Consortium buying for corrugated boxes. The 20000+ tier unlocks 28% savings. Ideal for FMCG distributors, manufacturers, and exporters across Nigeria.",
    participants: [
      { id: "p12", name: "FMCG Distributors Lagos", quantity: 5000, joinedAt: "2025-01-10" },
      { id: "p13", name: "Export Packers Ltd", quantity: 8000, joinedAt: "2025-01-14" },
      { id: "p14", name: "Manufacturers Association", quantity: 6000, joinedAt: "2025-01-19" },
    ],
  },
];

export const creditProfiles: CreditProfile[] = [
  {
    id: "credit_1",
    businessName: "Chidi's Retail Mart",
    ownerName: "Chidi Okonkwo",
    monthlyVolume: 4500000,
    fulfillmentRate: 94,
    creditScore: 685,
    maxCreditLimit: 3500000,
    activeBnplAmount: 1200000,
    riskGrade: "B+",
    transactionHistory: [
      { date: "2024-10-01", type: "sale", amount: 450000, description: "Lagos wholesale order" },
      { date: "2024-10-15", type: "purchase", amount: 280000, description: "Cotton fabric restock" },
      { date: "2024-11-01", type: "bnpl", amount: 1200000, description: "BNPL - Leather soles" },
      { date: "2024-11-10", type: "repayment", amount: 400000, description: "BNPL installment 1/3" },
      { date: "2024-11-20", type: "sale", amount: 520000, description: "Kano bulk order" },
    ],
  },
  {
    id: "credit_2",
    businessName: "Aba Leather Works Ltd",
    ownerName: "Adebayo Ogunlesi",
    monthlyVolume: 8200000,
    fulfillmentRate: 98,
    creditScore: 745,
    maxCreditLimit: 8000000,
    activeBnplAmount: 3000000,
    riskGrade: "A",
    transactionHistory: [
      { date: "2024-09-01", type: "sale", amount: 1200000, description: "Export order - Ghana" },
      { date: "2024-10-05", type: "purchase", amount: 850000, description: "Raw hide purchase" },
      { date: "2024-11-01", type: "bnpl", amount: 3000000, description: "Equipment upgrade loan" },
    ],
  },
  {
    id: "credit_3",
    businessName: "Emeka's Wholesale Goods",
    ownerName: "Emeka Nwosu",
    monthlyVolume: 2100000,
    fulfillmentRate: 82,
    creditScore: 520,
    maxCreditLimit: 1000000,
    activeBnplAmount: 800000,
    riskGrade: "C",
    transactionHistory: [
      { date: "2024-08-15", type: "sale", amount: 180000, description: "Onitsha market supply" },
      { date: "2024-09-20", type: "bnpl", amount: 800000, description: "BNPL - Packaging materials" },
      { date: "2024-10-10", type: "repayment", amount: 200000, description: "Partial repayment" },
    ],
  },
  {
    id: "credit_4",
    businessName: "Ibadan Agro Processors",
    ownerName: "Funke Adeyemi",
    monthlyVolume: 5800000,
    fulfillmentRate: 96,
    creditScore: 710,
    maxCreditLimit: 5000000,
    activeBnplAmount: 1500000,
    riskGrade: "A-",
    transactionHistory: [
      { date: "2024-10-01", type: "sale", amount: 900000, description: "Cassava flour bulk order" },
      { date: "2024-11-01", type: "bnpl", amount: 1500000, description: "Processing equipment BNPL" },
      { date: "2024-11-15", type: "repayment", amount: 500000, description: "BNPL installment 1/3" },
    ],
  },
];

export const orders: Order[] = [
  {
    id: "ord_1",
    buyerName: "Chidi's Retail Mart",
    buyerId: "user_1",
    items: [
      { productId: "prod_1", productTitle: "Premium Aba Leather Soles", quantity: 1000, unitPrice: 780 },
      { productId: "prod_3", productTitle: "Ibadan Premium Cassava Flour", quantity: 500, unitPrice: 400 },
    ],
    totalAmount: 980000,
    paymentType: "bnpl",
    status: "processing",
    deliveryRoute: "Aba - Ibadan - Lagos",
    createdAt: "2025-01-10",
    estimatedDelivery: "2025-01-20",
    tracking: [
      { status: "confirmed", location: "Aba", timestamp: "2025-01-10 09:00", description: "Order confirmed by seller" },
      { status: "processing", location: "Aba", timestamp: "2025-01-12 14:00", description: "Goods being packaged for dispatch" },
    ],
  },
  {
    id: "ord_2",
    buyerName: "Emeka's Wholesale Goods",
    buyerId: "user_4",
    items: [
      { productId: "prod_4", productTitle: "Corrugated Packaging Boxes", quantity: 5000, unitPrice: 155 },
    ],
    totalAmount: 775000,
    paymentType: "direct",
    status: "delivered",
    deliveryRoute: "Lagos - Onitsha",
    createdAt: "2025-01-05",
    estimatedDelivery: "2025-01-12",
    tracking: [
      { status: "confirmed", location: "Lagos", timestamp: "2025-01-05 10:00", description: "Order confirmed" },
      { status: "shipped", location: "Lagos", timestamp: "2025-01-07 08:00", description: "Dispatched from warehouse" },
      { status: "delivered", location: "Onitsha", timestamp: "2025-01-11 16:00", description: "Delivered to buyer" },
    ],
  },
  {
    id: "ord_3",
    buyerName: "Chidi's Retail Mart",
    buyerId: "user_1",
    items: [
      { productId: "prod_2", productTitle: "Organic Cotton Bales", quantity: 200, unitPrice: 2950 },
    ],
    totalAmount: 590000,
    paymentType: "direct",
    status: "shipped",
    deliveryRoute: "Kano - Lagos",
    createdAt: "2025-01-12",
    estimatedDelivery: "2025-01-18",
    tracking: [
      { status: "confirmed", location: "Kano", timestamp: "2025-01-12 11:00", description: "Order confirmed" },
      { status: "shipped", location: "Kano", timestamp: "2025-01-14 06:00", description: "Dispatched from Kano" },
    ],
  },
  {
    id: "ord_4",
    buyerName: "Emeka's Wholesale Goods",
    buyerId: "user_4",
    items: [
      { productId: "prod_8", productTitle: "Kano Organic Shea Butter", quantity: 100, unitPrice: 2500 },
    ],
    totalAmount: 250000,
    paymentType: "bnpl",
    status: "pending",
    deliveryRoute: "Kano - Onitsha",
    createdAt: "2025-01-15",
    estimatedDelivery: "2025-01-22",
    tracking: [
      { status: "pending", location: "Kano", timestamp: "2025-01-15 09:00", description: "Awaiting seller confirmation" },
    ],
  },
];

export const logisticsRoutes: LogisticsRoute[] = [
  {
    id: "route_1",
    from: "Lagos (Ikeja)",
    to: "Ibadan",
    distanceKm: 125,
    estimatedHours: 2.5,
    freightCostPerKg: 45,
    bulkDiscountThreshold: 5000,
    bulkDiscountPct: 15,
  },
  {
    id: "route_2",
    from: "Lagos (Ikeja)",
    to: "Onitsha",
    distanceKm: 480,
    estimatedHours: 8,
    freightCostPerKg: 120,
    bulkDiscountThreshold: 3000,
    bulkDiscountPct: 12,
  },
  {
    id: "route_3",
    from: "Aba",
    to: "Lagos (Ikeja)",
    distanceKm: 565,
    estimatedHours: 9,
    freightCostPerKg: 130,
    bulkDiscountThreshold: 3000,
    bulkDiscountPct: 10,
  },
  {
    id: "route_4",
    from: "Kano",
    to: "Lagos (Ikeja)",
    distanceKm: 1100,
    estimatedHours: 16,
    freightCostPerKg: 200,
    bulkDiscountThreshold: 2000,
    bulkDiscountPct: 15,
  },
  {
    id: "route_5",
    from: "Kano",
    to: "Kaduna",
    distanceKm: 200,
    estimatedHours: 3.5,
    freightCostPerKg: 60,
    bulkDiscountThreshold: 5000,
    bulkDiscountPct: 10,
  },
  {
    id: "route_6",
    from: "Aba",
    to: "Onitsha",
    distanceKm: 110,
    estimatedHours: 2,
    freightCostPerKg: 40,
    bulkDiscountThreshold: 5000,
    bulkDiscountPct: 20,
  },
  {
    id: "route_7",
    from: "Onitsha",
    to: "Lagos (Ikeja)",
    distanceKm: 480,
    estimatedHours: 8,
    freightCostPerKg: 115,
    bulkDiscountThreshold: 3000,
    bulkDiscountPct: 12,
  },
  {
    id: "route_8",
    from: "Ibadan",
    to: "Lagos (Ikeja)",
    distanceKm: 125,
    estimatedHours: 2.5,
    freightCostPerKg: 45,
    bulkDiscountThreshold: 5000,
    bulkDiscountPct: 15,
  },
];

export const deliveryRequests: DeliveryRequest[] = [
  {
    id: "del_1",
    routeId: "route_3",
    orderId: "ord_1",
    weightKg: 2500,
    status: "in_transit",
    cost: 292500,
    estimatedDelivery: "2025-01-20",
    tracking: [
      { status: "picked_up", location: "Aba", timestamp: "2025-01-13 08:00", description: "Goods picked up from Aba Leather Works" },
      { status: "in_transit", location: "Owerri", timestamp: "2025-01-13 14:00", description: "En route via Owerri-Ibadan corridor" },
    ],
  },
  {
    id: "del_2",
    routeId: "route_7",
    orderId: "ord_2",
    weightKg: 1800,
    status: "delivered",
    cost: 182160,
    estimatedDelivery: "2025-01-12",
    tracking: [
      { status: "picked_up", location: "Lagos", timestamp: "2025-01-07 08:00", description: "Picked up from Lagos Packaging Solutions" },
      { status: "in_transit", location: "Benin City", timestamp: "2025-01-08 11:00", description: "Passing through Benin City" },
      { status: "delivered", location: "Onitsha", timestamp: "2025-01-11 16:00", description: "Delivered to Emeka's Wholesale Goods" },
    ],
  },
  {
    id: "del_3",
    routeId: "route_4",
    orderId: "ord_3",
    weightKg: 600,
    status: "in_transit",
    cost: 102000,
    estimatedDelivery: "2025-01-18",
    tracking: [
      { status: "picked_up", location: "Kano", timestamp: "2025-01-14 06:00", description: "Picked up from Kano Textile Mills" },
      { status: "in_transit", location: "Kaduna", timestamp: "2025-01-14 12:00", description: "Arrived at Kaduna checkpoint" },
    ],
  },
];

export const collaterals: Collateral[] = [
  {
    id: "coll_1",
    producerId: "user_2",
    inventoryTitle: "Finished Leather Soles (50,000 pairs)",
    estimatedValue: 42500000,
    loanValue: 29750000,
    status: "active",
    createdAt: "2024-12-01",
  },
  {
    id: "coll_2",
    producerId: "user_5",
    inventoryTitle: "Cassava Flour Stock (20,000 kg)",
    estimatedValue: 9000000,
    loanValue: 5400000,
    status: "active",
    createdAt: "2024-12-15",
  },
  {
    id: "coll_3",
    producerId: "user_2",
    inventoryTitle: "Cotton Fabric Rolls (10,000 meters)",
    estimatedValue: 8500000,
    loanValue: 5950000,
    status: "released",
    createdAt: "2024-10-01",
  },
];

export const bnplApplications: BNPLApplication[] = [
  {
    id: "bnpl_1",
    buyerId: "user_1",
    buyerName: "Chidi's Retail Mart",
    amount: 1200000,
    termDays: 60,
    interestRate: 8,
    monthlyPayment: 648000,
    status: "active",
    productId: "prod_1",
    productTitle: "Premium Aba Leather Soles",
    appliedAt: "2025-01-08",
    approvedAt: "2025-01-09",
    repayments: [
      { dueDate: "2025-02-09", amount: 648000, paid: true, paidAt: "2025-02-08" },
      { dueDate: "2025-03-09", amount: 648000, paid: false },
    ],
  },
  {
    id: "bnpl_2",
    buyerId: "user_4",
    buyerName: "Emeka's Wholesale Goods",
    amount: 800000,
    termDays: 30,
    interestRate: 6,
    monthlyPayment: 848000,
    status: "active",
    productId: "prod_4",
    productTitle: "Corrugated Packaging Boxes",
    appliedAt: "2025-01-10",
    approvedAt: "2025-01-11",
    repayments: [
      { dueDate: "2025-02-11", amount: 848000, paid: false },
    ],
  },
  {
    id: "bnpl_3",
    buyerId: "user_5",
    buyerName: "Ibadan Agro Processors",
    amount: 1500000,
    termDays: 90,
    interestRate: 10,
    monthlyPayment: 550000,
    status: "active",
    productId: "prod_10",
    productTitle: "Ibadan Soybean Cake",
    appliedAt: "2025-01-05",
    approvedAt: "2025-01-06",
    repayments: [
      { dueDate: "2025-02-06", amount: 550000, paid: true, paidAt: "2025-02-04" },
      { dueDate: "2025-03-06", amount: 550000, paid: false },
      { dueDate: "2025-04-06", amount: 550000, paid: false },
    ],
  },
];

export const platformMetrics: PlatformMetrics = {
  totalTransactions: 1247,
  totalVolume: 2850000000,
  activePools: 4,
  totalSavings: 156000000,
  creditDistributed: 42000000,
  fulfillmentRate: 94,
  activeUsers: 342,
  registeredProducers: 86,
};

export const regions = ["Lagos", "Aba", "Kano", "Ibadan", "Onitsha", "Nnewi"] as const;
export const categories = [
  "Agro-Processing",
  "Textiles & Apparel",
  "Footwear & Leather",
  "Plastics & Packaging",
  "Light Machinery",
  "Chemical Raw Materials",
] as const;